before_install:
  - make install
script:
  - make test-ci
  - make build
before_deploy:
  - rm -rf ./node_modules
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: hexlet-learning-slack
  skip_cleanup: true
  on:
    tags: true